# Site settings
title: opsdroid | An open source python chat-ops bot
description: > # this means to ignore newlines until "baseurl:"
  An open source python chat-ops bot
baseurl: "" # the subpath of your site, e.g. /blog/
url: "opsdroid.github.io" # the base hostname & protocol for your site
twitter_username: opsdroid
github_username:  opsdroid
dockerhub_username: opsdroid
google_analytics: UA-83009564-1

# Build settings
markdown: kramdown
